### ISSUE TITLE
Project configuration

### ISSUE THREAD

**Issue by ghost** [passcod/cargo-watch#120]
It would be nice to be able to configure default `-w` and `-i` directories so that I don't have to include them with every command.

This is getting complicated:

```
cargo watch -w Cargo.toml -w examples -w src -w templates -c -x "run --example readme_example_2"
```

**Comment by passcod** [comment]
[cargo make](https://github.com/sagiegurari/cargo-make) is great tool that does pretty much all that! I actually thought I had it in the readme. It invokes cargo watch internally; it has a config, you can write down options, commands, etc; you can have multiple watch tasks to support different cases, including variadic, e.g.

```toml
[tasks.watch-example]
command = "cargo"
args = [ "run", "--example", "${example}" ]
watch = true
```

```bash
$ cargo make watch-example -e example=readme_example_2
```

It may not currently support some watch options, so there may be some feature requests needed, but it's probably a good start anyway.
